"""The host allow-list, as configuration for the thing that can enforce it.

frost checks `require reaching only` against the script before it runs, and
now also against a command's real arguments at the moment before `execve`.
Neither is a boundary. A program that ignores its arguments and dials out on
its own is untouched by both, and the only thing that stops it is a proxy or a
firewall.

Those live outside frost, which is fine, except that it leaves two lists: the
one in the policy that review reads, and the one in the proxy that actually
holds. They drift, nobody compares them, and the drift is invisible until it
matters.

So frost writes the second from the first.

    frost --egress-rules squid --policy prod.policy > frost.acl

## Why a proxy and not a packet filter

A hostname allow-list is not something a packet filter can express. nftables
and iptables match addresses; a name has to be resolved first, resolutions
change, one address can serve many names and one name many addresses. Emitting
an nftables ruleset from hostnames would produce a file that looks like
enforcement and is wrong the first time a CDN rotates.

A forward proxy sees the name in `CONNECT` or in the request line, which is
the layer where this rule can be stated exactly. So that is what is emitted,
and the plain list is there for whatever else already exists.
"""
# SPDX-License-Identifier: MIT

FORMATS = ("squid", "list")

HEADER = """# Generated by `frost --egress-rules {format}` from {source}.
#
# This is the same allow-list the policy states and `--explain` reports. Both
# come from one file so they cannot drift, which is the only reason to
# generate it rather than write it twice.
#
# frost checks this list against the script before it runs, and against a
# command's real arguments in the moment before it spawns. Neither is a
# boundary: a program that ignores its arguments and dials out on its own is
# stopped by this proxy and by nothing else.
"""


def hosts_from(rules):
    """Every host an allow-list rule names, in the order they were written."""
    out = []
    for rule in rules:
        if rule.kind != "reach_only":
            continue
        for host in rule.detail or []:
            if host not in out:
                out.append(host)
    return out


def denied_from(rules):
    out = []
    for rule in rules:
        if rule.kind == "reach" and rule.severity == "forbid":
            if rule.subject not in out:
                out.append(rule.subject)
    return out


def _squid_pattern(host):
    """A frost glob as a Squid dstdomain.

    `*.internal` is `.internal` to Squid, which matches the domain and every
    subdomain. A bare name is itself. Anything with a glob in the middle has
    no dstdomain equivalent and is emitted as a regex instead, so the rule is
    still expressed rather than quietly dropped.
    """
    if host.startswith("*."):
        return "dstdomain", "." + host[2:]
    if "*" in host or "?" in host or "[" in host:
        pattern = (host.replace(".", r"\.").replace("*", ".*")
                       .replace("?", "."))
        return "dstdom_regex", f"^{pattern}$"
    return "dstdomain", host


def squid(rules, source="a policy"):
    allowed, denied = hosts_from(rules), denied_from(rules)
    out = [HEADER.format(format="squid", source=source)]

    if denied:
        out.append("# Refused outright, whatever else allows them.")
        for host in denied:
            kind, pattern = _squid_pattern(host)
            out.append(f"acl frost_denied {kind} {pattern}")
        out.append("http_access deny frost_denied")
        out.append("")

    if allowed:
        out.append("# The allow-list.")
        for host in allowed:
            kind, pattern = _squid_pattern(host)
            out.append(f"acl frost_allowed {kind} {pattern}")
        out.append("http_access allow frost_allowed")
        out.append("")
        out.append("# Everything the policy did not name. Without this line "
                   "the allow-list")
        out.append("# is a suggestion, because Squid's default is to fall "
                   "through.")
        out.append("http_access deny all")
    else:
        out.append("# The policy names no allow-list, so there is nothing to")
        out.append("# generate. Add: require reaching only \"api.example\"")

    return "\n".join(out).rstrip() + "\n"


def plain(rules, source="a policy"):
    """One host per line, for whatever configuration already exists."""
    allowed = hosts_from(rules)
    out = [HEADER.format(format="list", source=source)]
    out.extend(allowed)
    if not allowed:
        out.append("# The policy names no allow-list.")
    return "\n".join(out).rstrip() + "\n"


def render(fmt, rules, source="a policy"):
    if fmt == "squid":
        return squid(rules, source)
    if fmt == "list":
        return plain(rules, source)
    raise ValueError(f"unknown format {fmt!r}; try one of {', '.join(FORMATS)}")
