#!/usr/bin/env python3
"""Write frost.1 from the argument parser itself.

A man page maintained by hand is a man page that describes last year's flags.
This one is generated from the same parser the CLI uses and the tests already
introspect, so a flag that is added, renamed or removed shows up here or the
generated-files check fails.

Prose that is not a flag lives in this file. The parser knows what the options
are and nothing about why anyone would want them.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from frostlang import __version__, cli          # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(REPO, "frost.1")

HEAD = r'''.\" Generated by tools/build_man.py. Do not edit.
.TH FROST 1 "" "frost {version}" "User Commands"
.SH NAME
frost \- a readable shell scripting language that is auditable before it runs
.SH SYNOPSIS
.B frost
[\fIOPTION\fR]... \fISCRIPT\fR
.br
.B frost
.I init
[\fIFOLDER\fR]
.br
.B frost
.I diff
\fIBEFORE\fR \fIAFTER\fR
.br
.B frost
.I mcp
|
.I context
|
.I keystore
.SH DESCRIPTION
frost runs shell scripts that can be read before they are run. A command is
argv and never a string, so a value can never become syntax: there is no
.BR eval ,
no command substitution and no string interpolation to represent.
.PP
Because every effect is a node in the tree, frost can print a capability
manifest before a single process is spawned, and a policy can refuse a script
that does more than it was meant to.
.PP
\fISCRIPT\fR may be a file, a folder whose \fB.frost\fR files are all
reviewed, or \fB\-\fR to read one script from standard input.
.SH OPTIONS
'''

TAIL = r'''.SH EXIT STATUS
.TP
.B 0
the script ran and finished
.TP
.B 1
a command failed, or the script hit a runtime error
.TP
.B 2
it did not parse, or frost was asked for something it could not set up
.TP
.B 3
a policy, an import ceiling, a sandbox boundary or an approval said no;
nothing ran
.TP
.B 4
a replay did not match its recording
.TP
.B 124
the run passed its deadline
.TP
.B 125
the run passed a volume ceiling
.SH ENVIRONMENT
.TP
.B NO_COLOR
disable colour, whatever the terminal says
.TP
.B FROST_SITE_POLICY_DIR
a folder of policies applied to every run, which can only add rules
.TP
.B FROST_AUTOMATED
treat the run as unattended, refusing to approve or to draft a policy change
.SH FILES
.TP
.B frost.policy
found beside the script, or above it, and applied unless \fB\-\-no\-policy\fR
.SH SEE ALSO
The full reference is LANGUAGE.md in the distribution, and
.UR https://github.com/keithadler/frost
.UE .
'''


def escape(text):
    return text.replace("\\", "\\\\").replace("-", r"\-")


def render():
    parser = cli.build_parser()
    out = [HEAD.format(version=__version__)]
    for action in parser._actions:
        if not action.option_strings or action.help == "==SUPPRESS==":
            continue
        flags = ", ".join(f"\\fB{escape(f)}\\fR" for f in action.option_strings)
        if action.metavar:
            flags += f" \\fI{action.metavar}\\fR"
        out.append(".TP\n" + flags + "\n" + escape(action.help or "") + "\n")
    out.append(TAIL)
    return "".join(out)


if __name__ == "__main__":
    with open(TARGET, "w") as fh:
        fh.write(render())
    print(f"wrote {TARGET} ({os.path.getsize(TARGET):,} bytes)")
